# Generated by Django 3.2.9 on 2024-01-28 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=70)),
                ('firstname', models.CharField(max_length=70)),
                ('age', models.IntegerField(default=0)),
                ('xuruj_count', models.IntegerField(default=0)),
                ('medic_count', models.IntegerField(default=0)),
                ('is_xuruj', models.BooleanField(default=False)),
                ('date_times', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('amount', models.CharField(max_length=200)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medics', to='chat.sick')),
            ],
        ),
        migrations.CreateModel(
            name='Huruj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_times', models.DateTimeField(auto_now_add=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hurujs', to='chat.sick')),
            ],
        ),
    ]
