# Generated by Django 3.2.9 on 2024-01-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20240131_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sick',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='sick',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='sick',
            name='medic_count',
        ),
        migrations.AddField(
            model_name='sick',
            name='username',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sick',
            name='dori_miqdor',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='sick',
            name='dori_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='sick',
            name='kasal_name',
            field=models.CharField(max_length=400),
        ),
    ]
