# Generated by Django 3.2.6 on 2024-02-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20240131_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Huruj',
        ),
    ]
