# Generated by Django 3.2.6 on 2024-03-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_xulosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sick',
            name='xulosa',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Xulosa',
        ),
    ]
