# Generated by Django 3.2.6 on 2024-03-11 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20240306_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sick',
            name='xulosa',
        ),
        migrations.CreateModel(
            name='Xulosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_times', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=400)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xulosa', to='chat.sick')),
            ],
        ),
    ]
